# H2 콘솔 사용
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    hikari:
      maximum-pool-size: 4

# MyBatis 설정
# mapper.xml 위치
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.model